# Generated by Django 4.2.13 on 2024-07-02 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'equipe',
            },
        ),
        migrations.CreateModel(
            name='EquipePersonnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personnel_id', models.IntegerField()),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gmao_teams.equipe')),
            ],
            options={
                'db_table': 'equipe_personnel',
                'unique_together': {('equipe', 'personnel_id')},
            },
        ),
        migrations.CreateModel(
            name='DoleanceEquipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doleance_id', models.IntegerField()),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gmao_teams.equipe')),
            ],
            options={
                'db_table': 'doleance_equipe',
                'unique_together': {('equipe', 'doleance_id')},
            },
        ),
    ]
