# Generated by Django 4.2.13 on 2024-07-04 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_employee_first_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
