# Generated by Django 4.2.13 on 2024-07-01 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Air',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_contrat', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'air',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AppareilDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_serie', models.CharField(max_length=50)),
                ('type_contrat', models.CharField(max_length=10)),
                ('annee_installation', models.IntegerField(blank=True, null=True)),
                ('face_principal', models.IntegerField(blank=True, null=True)),
                ('face_secondaire', models.IntegerField(blank=True, null=True)),
                ('is_face_unique', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'appareil_distribution',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Appelant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_appelant', models.CharField(max_length=50)),
                ('prenom_appelant', models.CharField(max_length=255)),
                ('email_appelant', models.CharField(max_length=50)),
                ('num_appelant', models.CharField(blank=True, max_length=13, null=True)),
            ],
            options={
                'db_table': 'appelant',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Auvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_contrat', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'auvent',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BonEntree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_be', models.IntegerField()),
            ],
            options={
                'db_table': 'bon_entree',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BonSortie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_bs', models.IntegerField()),
            ],
            options={
                'db_table': 'bon_sortie',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Boutique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'boutique',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_client', models.CharField(max_length=191, unique=True)),
                ('num_prefix', models.SmallIntegerField(unique=True)),
            ],
            options={
                'db_table': 'client',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Compresseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pression', models.IntegerField()),
                ('debit', models.IntegerField()),
                ('puissance', models.IntegerField()),
                ('annee', models.IntegerField()),
                ('type_contrat', models.CharField(max_length=50)),
                ('capacite', models.IntegerField()),
            ],
            options={
                'db_table': 'compresseur',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cuve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=50)),
                ('type_contrat', models.CharField(max_length=10)),
                ('capacite', models.IntegerField()),
            ],
            options={
                'db_table': 'cuve',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Doleance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_transmission', models.DateTimeField(blank=True, null=True)),
                ('ndi', models.CharField(max_length=255)),
                ('date_deadline', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('NEW', 'Nouvelle'), ('ATT', 'En attente'), ('INT', 'En intervention'), ('ATP', 'Attente pièces'), ('ATD', 'Attente devis'), ('TER', 'Terminée')], default='NEW', max_length=20)),
                ('type_transmission', models.CharField(max_length=50)),
                ('panne_declarer', models.TextField()),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('date_debut', models.DateTimeField(blank=True, null=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('element', models.CharField(blank=True, max_length=255, null=True)),
                ('bt', models.CharField(blank=True, max_length=11, null=True)),
                ('type_contrat', models.CharField(max_length=10)),
                ('is_facture', models.IntegerField(blank=True, null=True)),
                ('num_facture', models.CharField(blank=True, max_length=25, null=True)),
            ],
            options={
                'db_table': 'doleance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EclairageAuvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_contrat', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'eclairage_auvent',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EclairageBoutique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_contrat', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'eclairage_boutique',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EclairageElectricite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_contrat', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'eclairage_electricite',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EclairageServicing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_contrat', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'eclairage_servicing',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EclairageTotem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_contrat', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'eclairage_totem',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Elec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'elec',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fournissseur', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'fournisseur',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Froid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_contrat', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'froid',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GroupeElectrogene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_contrat', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'groupe_electrogene',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_depart', models.DateTimeField(blank=True, null=True)),
                ('top_debut', models.DateTimeField(blank=True, null=True)),
                ('top_terminer', models.DateTimeField(blank=True, null=True)),
                ('duree_intervention', models.BigIntegerField(blank=True, null=True)),
                ('kilometrage_depart_debut', models.IntegerField(blank=True, null=True)),
                ('kilometrage_home', models.IntegerField(blank=True, null=True)),
                ('is_done', models.IntegerField()),
                ('is_half_done', models.IntegerField()),
                ('is_going_home', models.IntegerField()),
                ('etat_doleance', models.CharField(blank=True, max_length=20, null=True)),
                ('resolution', models.TextField(blank=True, null=True)),
                ('numero_fiche', models.CharField(blank=True, max_length=7, null=True, unique=True)),
            ],
            options={
                'db_table': 'intervention',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lavage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_contrat', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'lavage',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_contrat', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'lub',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MarqueAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle_marque', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'marque_ad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MarqueCompresseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle_marque', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'marque_compresseur',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MarqueGroupeElectrogene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle_marque', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'marque_groupe_electrogene',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MarquePistoletCompresseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle_marque', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'marque_pistolet_compresseur',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MigrationVersions',
            fields=[
                ('version', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('executed_at', models.DateTimeField(db_comment='(DC2Type:datetime_immutable)')),
            ],
            options={
                'db_table': 'migration_versions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Modele',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'modele',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModeleAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle_modele', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'modele_ad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModeleAir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle_modele', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'modele_air',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModeleAuvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle_modele', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'modele_auvent',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModeleCompresseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle_modele', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'modele_compresseur',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModeleEclairageAuvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle_modele', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'modele_eclairage_auvent',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModeleEclairageBoutique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle_modele', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'modele_eclairage_boutique',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModeleEclairageElectricite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle_modele', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'modele_eclairage_electricite',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModeleEclairageServicing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle_modele', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'modele_eclairage_servicing',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModeleEclairageTotem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle_modele', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'modele_eclairage_totem',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModeleFroid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle_modele', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'modele_froid',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModeleGroupeElectrogene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle_modele', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'modele_groupe_electrogene',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModeleLavage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle_modele', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'modele_lavage',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModeleLub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle_modele', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'modele_lub',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModelePrise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle_modele', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'modele_prise',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModeleTgbt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle_modele', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'modele_tgbt',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModeleTotem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle_modele', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'modele_totem',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_personnel', models.CharField(max_length=255)),
                ('prenom_personnel', models.CharField(max_length=255)),
                ('matricule', models.CharField(max_length=10, unique=True)),
                ('statut', models.CharField(choices=[('PRS', 'Présent'), ('ABS', 'Absent'), ('ATT', 'Tâche Attribuée'), ('INT', 'En intervention')], default='ABS', max_length=3)),
                ('num1', models.CharField(blank=True, max_length=13, null=True)),
                ('num2', models.CharField(blank=True, max_length=13, null=True)),
                ('num3', models.CharField(blank=True, max_length=13, null=True)),
                ('adresse', models.CharField(blank=True, max_length=50, null=True)),
                ('last_visite_medical', models.DateTimeField(blank=True, null=True)),
                ('cin', models.CharField(blank=True, max_length=12, null=True)),
                ('is_active', models.IntegerField()),
            ],
            options={
                'db_table': 'personnel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piece_libelle', models.CharField(max_length=255)),
                ('piece_reference', models.CharField(max_length=255)),
                ('constructeur_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('prix_achat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('entree', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sortie', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_actuelle', models.DecimalField(decimal_places=2, max_digits=10)),
                ('seuil', models.CharField(max_length=255)),
                ('valeur', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_securite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observation', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'piece',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PieceDevis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designations', models.CharField(max_length=255)),
                ('quantite', models.IntegerField()),
            ],
            options={
                'db_table': 'piece_devis',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PieceEntree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_entree', models.DateField()),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=12)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valeur', models.DecimalField(decimal_places=2, max_digits=12)),
                ('num_facture', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'piece_entree',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PieceIntervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sortie', models.DateField()),
                ('num_bt', models.CharField(blank=True, max_length=100, null=True)),
                ('num_bc', models.CharField(blank=True, max_length=100, null=True)),
                ('sortie_provisoire', models.DecimalField(decimal_places=2, max_digits=5)),
                ('retour', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sortie_reelle', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'piece_intervention',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Piste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ilot', models.IntegerField()),
            ],
            options={
                'db_table': 'piste',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pistolet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_contrat', models.CharField(max_length=10)),
                ('date_flexible', models.CharField(blank=True, max_length=4, null=True)),
                ('orientation', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'pistolet',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PistoletCompresseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_contrat', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'pistolet_compresseur',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pointage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_heure_arrive', models.DateTimeField(blank=True, null=True)),
                ('date_heure_sortie', models.DateTimeField(blank=True, null=True)),
                ('seconde_actif', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pointage',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Poste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_poste', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'poste',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Prise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_contrat', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'prise',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_produit', models.CharField(max_length=50)),
                ('code_produit', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'produit',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Servicing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'servicing',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lieu_station', models.CharField(max_length=50)),
                ('province_station', models.CharField(max_length=50)),
                ('libelle_station', models.CharField(max_length=50)),
                ('type_contrat', models.CharField(max_length=10)),
                ('have_servicing', models.IntegerField()),
                ('have_boutique', models.IntegerField()),
            ],
            options={
                'db_table': 'station',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tgbt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_contrat', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'tgbt',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Totem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_contrat', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'totem',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TypeAir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle_type', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'type_air',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TypeCompresseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle_type', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'type_compresseur',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TypeEclairageAuvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle_type', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'type_eclairage_auvent',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TypeEclairageBoutique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle_type', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'type_eclairage_boutique',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TypeEclairageElectricite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle_type', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'type_eclairage_electricite',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TypeEclairageServicing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle_type', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'type_eclairage_servicing',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TypeEclairageTotem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle_type', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'type_eclairage_totem',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TypeFroid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle_type', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'type_froid',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TypeGroupeElectrogene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle_type', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'type_groupe_electrogene',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TypeLavage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle_type', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'type_lavage',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TypeLub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle_type', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'type_lub',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TypePiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle_type', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'type_piece',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TypePistoletCompresseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle_type', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'type_pistolet_compresseur',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TypePrise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle_type', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'type_prise',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TypeTgbt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle_type', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'type_tgbt',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UnitePiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unite', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'unite_piece',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=180, unique=True)),
                ('roles', models.TextField()),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle_vehicule', models.CharField(max_length=255)),
                ('marque_vehicule', models.CharField(max_length=50)),
                ('numero_vehicule', models.CharField(max_length=50)),
                ('kilometrage_vehicule', models.IntegerField(blank=True, null=True)),
                ('limit_assurance', models.DateTimeField(blank=True, null=True)),
                ('last_visite_technique', models.DateTimeField(blank=True, null=True)),
                ('last_vidange', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'vehicule',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InterventionPersonnel',
            fields=[
                ('intervention', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='gmao.intervention')),
            ],
            options={
                'db_table': 'intervention_personnel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InterventionVehicule',
            fields=[
                ('intervention', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='gmao.intervention')),
            ],
            options={
                'db_table': 'intervention_vehicule',
                'managed': False,
            },
        ),
    ]
